### ISSUE TITLE
Properties generating functions/use unknown "types" will run forever

### ISSUE THREAD

**Issue by neshtea** [active-group/active-quickcheck#4]
Using the `property`-macro for generating functions, it will run forever when choosing an "unknown" codomain (such as `int` instead of `integer` in the example below).

```
(ns active-quickcheck-example.core-test
  (:require [active.quickcheck :as qs]))

;; This one works.
(qs/quickcheck
 (qs/property [f (boolean -> boolean)]
              (boolean? (f))))

;; => OK, passed 100 tests.

;; This will run forever (?).
(qs/quickcheck
 (qs/property [i int
               f (int -> int)]
              (int? (f i))))

```

It would be helpful to notify the user that something went wrong.

**Comment by dfrese** [comment]
Findings:
- only hangs when both fn and the argument is generated.
- 'int' is not unknown; the problem must be something else.

**Comment by markusschlegel** [comment]
The problem is the `variant` monad primitive, which should have constant time complexity but is linear or even worse. In the following snippet, taken from the implementation of `variant`, `v` is the input (`i` in the code snippet above).

```clojure
...
(loop [v (+ 1 v)
                 rgen rgen]
            (if (zero? v)
              (run (variant-generator m) size rgen)
              (let [[_ rgen2] (random-generator-split rgen v)]
                (run (variant-generator m) size rgen2))))
```

A better version of `variant` should use a special `random-generator-split` function that performs these many loop iterations in a single step.

**Comment by markusschlegel** [comment]
Not a single step, but now logarithmic complexity with 396cea6cb417360f81f6d220eeed5090095e9ca0
